#include <iostream>
using namespace std;
int main(){
    try { 
        try {
            throw 20;
        }
        catch (int n) {
            cout << "Manejado parcialmente " <<endl;
            throw; // Relanzando una excepciÃ³n
        }
    }
    catch (int n) {
        cout << "Manejando el resto " <<endl;
    }
    return 0;
}